  - name: Checkout the branch
    uses: actions/checkout@v1
  - name: Install flutter
    uses: subosito/flutter'action@v1
    with:
      channel: 'stable'
  - name: Get packages
    run: flutter pub get
  - name: Build runner
    run: flutter pub run build_runner build