name: CI/CD INIT

on: 
  push:
    branches:
      - main
  pull_request:  

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v1
      - name: Install flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: 'stable'
          flutter-version-file: pubspec.yaml
      - name: Get packages
        run: flutter pub get
      - name: Flutter version
      - run: flutter --version
      - name: Build runner
        run: flutter pub run build_runner build

